USE [master]
GO

/****** Object:  Database [Lab12]    Script Date: 17.11.2019 3:05:30 ******/
CREATE DATABASE [Lab12]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lab12', FILENAME = N'D:\Programm\Программирование\MySql\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Lab12.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lab12_log', FILENAME = N'D:\Programm\Программирование\MySql\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Lab12_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Lab12] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lab12].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lab12] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lab12] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lab12] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lab12] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lab12] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lab12] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lab12] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lab12] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lab12] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lab12] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lab12] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lab12] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lab12] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lab12] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lab12] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lab12] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lab12] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lab12] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lab12] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lab12] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lab12] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lab12] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lab12] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Lab12] SET  MULTI_USER 
GO

ALTER DATABASE [Lab12] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lab12] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lab12] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lab12] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lab12] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lab12] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Lab12] SET  READ_WRITE 
GO


